### ISSUE TITLE
QC "Upload on-fly generated (by third-party scripts) images to GCS" option

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#107]
Check with @antonkorotkov to learn about this setting.

- [ ] What does it do exactly?
- [ ] and why does it include the warning: "This option may slow down file upload processes"

**Comment by antonkorotkov** [comment]
@ewsopp 
> What does it do exactly?

It adds a filter that is fired when some third-party plugin or theme uses WP Media API to resize images on demand when viewing a page for example. That way Stateless can handle images like that.

> and why does it include the warning: "This option may slow down file upload processes"

Warning is a bit incorrect. It should say something like "May slow down page loading speed". Because in fact it will try to upload images every time that filter fires. And it may happen on every page load.

This option was added to handle some custom case we encountered. There are only a few cases when it may help. So for the most configurations it should be disabled. I would even remove this option at all since third-party themes and plugins should not use media API directly to resize images but should add it's own image sizes. In other words I think handling of custom things is not Stateless problem.
