### ISSUE TITLE
disabling "Organization" setting not working

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#113]
If I have the "Organization" setting disabled, it still uploads files into year and month folders.

![image](https://user-images.githubusercontent.com/5578537/28169236-b0bdaea6-67af-11e7-90eb-87bfbbc7ec77.png)

**Comment by alimuzzaman** [comment]
@ewsopp @andypotanin Previously we used WordPress default  `Organize my uploads into month- and year-based folders` setting.
Can we use that? If value changes on our settings page we will update default wp setting on media.php! It would be easy and safe other than hooking into places.

**Comment by andypotanin** [comment]
@ewsopp @alimuzzaman I agree with @alimuzzaman it seems like this option would conflict/override/cause-unexpected-behaviour since WordPress has this already:
![image](https://user-images.githubusercontent.com/1255935/28236276-f3a146ec-68ef-11e7-8a85-8f5650769e0f.png)

We should not mess with the "base url" for media items, we could cause problems with other plugins and environments.
