### ISSUE TITLE
Site Performance Issues and MySQL Strain

### ISSUE THREAD

**Issue by andypotanin** [udx/wp-stateless#116]
From: https://wordpress.org/support/topic/site-performance-issues-and-mysql-strain/

---

First of all, our company is a big fan of your plugin and this has been a great solution for our needs.

We’ve been experiencing site performance issues for some time and have tracked it down to this plugin. Primarily about every hour we get a huge spike that can be seen in New Relic where this plugin will jump from low milliseconds to over 19 seconds. We’ve also seen a direct correlation in MySQL overview for a task called MySQL rele_postmeta select that will go from milliseconds to over 90 seconds. These are massive spikes and will often times cause our backend to crash for a few seconds and slows down other areas. But this plugin is putting a huge strain on database operations and our site.

Here are links to two screenshots:
![image](https://user-images.githubusercontent.com/1255935/28182859-710fadaa-67db-11e7-8528-a3d06a259fe5.png)

![image](https://user-images.githubusercontent.com/1255935/28182864-74bdabfa-67db-11e7-9814-612b2c657a22.png)

I would like to know if there is a way to fix or alleviate this problem, either through something I can change in the code or if this will be addressed with a future update? In regards to a future update, is there a timeline for when one will come or when compatibility will be updated? We are on version 4.8 and this plugin supports 4.5.9, and hasn’t seen an update in over a year. I can provide more screenshots and details if needed.

Thanks for your time.

**Comment by andypotanin** [comment]
It would help tremendously if we knew what sort of SQL queries were ran our the time of the spikes. We run wp-stateless on some fairly large sites with lots of Media and we have not noticed such spikes, nor have seen them reported, until now.

**Comment by Relevant-Brad** [comment]
I'll look into the SQL queries and post the findings as soon as I can find something concrete.

**Comment by andypotanin** [comment]
@Relevant-Brad also, do you have object cache setup on this site? Trying to get a better understanding of your environment.

**Comment by Relevant-Brad** [comment]
Currently object caching is not setup on the site. I'm trying to get very detailed information to send your way soon. I'm finding out this may be a false flag. Even though it listed wp-stateless as the issue, it appears that MySQL is account for nearly all the transaction made on the site. Yet, none of the database queries are connected to wp-stateless. I could not find db query connected to wp-stateless although New Relic reports it as being the slowest plugin on the site. Instead, I've found admin-ajax.php made a request to recurly.com which run equally slow. Also a plugin called Seriously Simple Podcasting could be a lot more to blame than it is currently showing. Sorry if this ends up being a non-issue, which is a shame because this is my personal favorite plugin we use on the site.

**Comment by ewsopp** [comment]
@Relevant-Brad - any update on your investigation?

**Comment by ewsopp** [comment]
I'm going to close this out for now. If you have any more useful details, please share and we can investigate further.
