### ISSUE TITLE
Consider using official Google API Client

### ISSUE THREAD

**Issue by ckeeney** [udx/wp-stateless#120]
This plugin depends on [UsabilityDynamics/google-api-php-client](https://github.com/UsabilityDynamics/google-api-php-client), a fork of [google/google-api-php-client](https://github.com/google/google-api-php-client).  The fork seems unmaintained, with the most recent commit nearly 1 year ago.  The only [commits added to the fork](https://github.com/google/google-api-php-client/compare/master...UsabilityDynamics:master) are to update `composer.json` to lock versions down into older versions.

Meanwhile, there are [62 commits](https://github.com/UsabilityDynamics/google-api-php-client/compare/master...google:master) added to the main repository that have not been merged back in.

I came across this because I wanted to add a `wp-cli` command to my site that relied on [google/google-api-php-client](https://github.com/google/google-api-php-client), but it was conflicting with the very outdated version required by this repo.

**Comment by andypotanin** [comment]
@pemaxim did we end up including this or did we give up due to WordPress.org SVN's size issues?

**Comment by ckeeney** [comment]
The latest version has in the changelog that it uses the official google sdk.  It doesn't use my commit because the dependency was taken out of composer, but I think this issue can probably be closed.

**Comment by pemaxim** [comment]
@ckeeney @andypotanin We did not include the latest Google SDK (v2.2.0) to the WP-Stateless v1.9.2 because there was an issue with committing it to WordPress SVN repository. The size of v2.2.0 is more than 29Mb, since it includes all services. And we have been facing with the timeouts on commit because of it.

So, I had to downgrade Google SDK to the version we had in WP-Stateless v1.9.0. And v1.9.2 still includes old Google SDK. 

Currently, we are thinking about using the only [Google Storage](https://github.com/GoogleCloudPlatform/google-cloud-php-storage) package in WP-Stateless instead of including full [Google SDK](https://github.com/google/google-api-php-client). [Google Storage](https://github.com/GoogleCloudPlatform/google-cloud-php-storage) package is mostly a part of [Google Cloud PHP](https://github.com/googlecloudplatform/google-cloud-php) package.

And, yes, @ckeeney you are correct, we moved Google SDK from `vendor` directory to prevent it to be loaded on every page load. It was done to solve the conflicts with the plugins/themes which may include older/newer Google SDK library. See the following topics:

* https://wordpress.org/support/topic/potential-plugin-conflict-with-updraft-backup/
* https://wordpress.org/support/topic/php-fatal-error-call-to-undefined-method-google_clientgetio/

By the way, UpdraftPlus WordPress Backup Plugin (mentioned in topics above) includes very old Google SDK - v1.1.4.
