### ISSUE TITLE
failover to image url if not found on disk

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#147]
- [x] if file is not found on disk or on configured GCS bucket, then...
- [x] try to fetch file from file URL (reference: https://codex.wordpress.org/Function_Reference/wp_remote_get)
- [x] When you are fetching the file remotely by the file URL, ensure that you are getting a 200 (OK) response.
- [x] store it temporarily to allow stateless to generate thumbnails (if it is an image) and store it correctly based on Mode setting (CDN, Local, or Stateless).
- [x] add support for images and non-images.

---

This is an important improvement for websites that have special redirection rules to load images from somewhere outside of the disk. We do this quite a bit for old client sites that have moved from different hosts.

**Comment by alimuzzaman** [comment]
@ewsopp 
> try to fetch image from URL 

Where from we will get the URL?

**Comment by andypotanin** [comment]
@alimuzzaman In our infrastructure we have special proxies to load files from a "backup" location if its missing in the container. So, if `site.com/wp-content/uploads/2017/01/some-file.png` is being resized, but there is no `/var/www/wp-content/uploads/2017/01/some-file.png` on disk, our proxy tries to load the image from a special bucket. (If it gets a 404 response, it "fails over", we call this technology "media failover" - it has nothing to do with WP-Stateless)

We do this because when we migrate a new site to our infrastructure we don't want to store all the media files with all the other files in Git, so we move all the `wp-content/uploads` files to a special bucket for the client.

All those files work but they are NOT properly stored/registered by WP-Stateless. They can be opened in a browser, or with cURL, but not by reading files from disk. 

We want to get all those files into the correct Google Cloud Storage bucket and have WP-Stateless manage them.

**Comment by alimuzzaman** [comment]
> store it temporarily to allow stateless to generate thumbnails and store it correctly based on Mode setting (CDN, Local, or Stateless).

Maybe we can just try to generate metadata on WordPress to work with the existing bucket.

**Comment by ewsopp** [comment]
@alimuzzaman please describe the steps in detail that WP-Stateless goes through when it encounters a media library object that has no WP-Stateless meta information during a sync.

**Comment by alimuzzaman** [comment]
Sync process:

1. We check if the image [exists on local disk](https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/class-ajax.php#L169).
2. If not it will [try to get the image from Google Storage](https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/class-ajax.php#L173).
3. If image also doesn't exist there it will [try to get the image via the URL](https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/class-ajax.php#L176) in case it's accessible via some sort of proxy.
4. If it's got the image from any one of the above methods it will start to [generate the thumbnails](https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/class-ajax.php#L185).
[This function](https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/class-utility.php#L145) hooked to wp_generate_attachment_metadata.

Most of the time 3 is unnecessary. So we can avoid that extra request using option.

**Comment by ewsopp** [comment]
Great writeup, and I appreciate the links you added. 

In step three, do you check the response of the URL? We should ensure a 200 response.

**Comment by alimuzzaman** [comment]
Yes, [checked for status](https://github.com/wpCloud/wp-stateless/blob/v2.1/lib/classes/class-ajax.php#L136) 200.
