### ISSUE TITLE
WP Stateless generates HTTPS links on website, but HTTP links in the media library

### ISSUE THREAD

**Issue by ahmed-sigmalux** [udx/wp-stateless#159]
When viewing https://www.mysite.com, all the CDN links inserted by WP Stateless also use HTTPS, e.g., https://cdn.mysite.com.

When viewing the media library from the admin panel, however, all the CDN links use HTTP, e.g., http://cdn.mysite.com.

This generates a mixed content warning by Chrome and, if you have a tight CSP, blocks the images from being loaded in the media library.

**Comment by alimuzzaman** [comment]
@ahmed-sigmalux What do you mean by https://cdn.mysite.com? Did you mean storage.googleapis.com?
Or you used a custom domain for CDN URL? If you use a custom domain you can't have https enabled. Google Storage doesn't support https for custom domains. In this case, the frontend should have also used http://cdn.mysite.com.
If you are not using custom domain we have to take a look.

**Comment by ahmed-sigmalux** [comment]
Sorry, let me provide some more context.

Yes, we are using a custom domain and, yes, we are using HTTPS. We are using Cloudflare, which is a Google Cloud partner (https://www.cloudflare.com/integrations/google-cloud/), meaning we can use a custom domain and SSL with Google Cloud storage buckets. Thus https://cdn.mysite.com is valid and works perfectly fine for our setup.

Cloudflare also rewrites HTTP URLs to HTTPS where possible - hence why our website has https://cdn.mysite.com on the frontend - but it doesn't work in all situations, apparently like the media library. In this case where Cloudflare cannot automatically rewrite the URLs to HTTPS, the HTTP links fail to load because our CSP doesn't allow any non-HTTPS content.

IMHO, the proper fix would be to let users choose between HTTP and HTTPS links whether they use a custom domain or googlestorageapis.com.

I hope that explanation makes more sense.

**Comment by alimuzzaman** [comment]
@ahmed-sigmalux We are working on it.

**Comment by alimuzzaman** [comment]
@ahmed-sigmalux Try this fix https://github.com/wpCloud/wp-stateless/tree/v2.1-hot-fix
Prefix the **Domain** with `https://`. Ex. https://cdn.mysite.com
Then try with a new photo to be sure and sync all the attachments. After sync, you will get https:// on all the attachments.

**Comment by ahmed-sigmalux** [comment]
I installed the hotfix and, when I enter https://cdn.mysite.com as the domain, the preview still shows https://storage.googleapis.com. Is that expected?

**Comment by ahmed-sigmalux** [comment]
Nevermind,  I see that I actually ended up with 2 version of the WP Stateless plugin.

Your hotfix works!

**Comment by dchenk** [comment]
This doesn’t appear to be solved fully; here’s the issue I’m having. I’ve got my media in a storage bucket which sits behind GCP’s load balancer with a TLS certificate. Based on the URL path, requests for media files are routed by the load balancer to the bucket—the request being done with my custom domain and secured with TLS. In the plugin’s settings, I’m able to specify a custom domain, but there is still the message showing “Be advised that the bucket name and domain name must match exactly and HTTPS is not supported with a custom domain.” In fact, however, it doesn’t matter what the bucket is named because requests are routed to it by the load balancer. I have the domain secured with the load balancer, and it knows where the “wp-content/uploads” files are (the bucket).

The problem is that the file URLs still have “storage.googleapis.com” —this is in the URL of thumbnails and featured images. Instead, it should just be: custom-domain.com/bucket-folder-path/file-path.jpg
... where “bucket-folder-path” is specified as a setting the way it’s currently done.

The solution is to make it possible to specify a custom and have the domain used in the main/default URL of media files.

Does this make sense? Can I clarify anything?

**Comment by dchenk** [comment]
Furthermore, when I insert media files into a post or page using the “Add Media” button above the editor, the selected image has “storage.googleapis.com/my-bucket-name” in the URL. This is highly undesirable for obvious reasons.
