### ISSUE TITLE
Programmatically adding Files

### ISSUE THREAD

**Issue by JessBoctor** [udx/wp-stateless#167]
Hello Again!

I have another puzzle I am hoping you could help me with.

I have a number of images which are created programmatically (pgraph charts) and saved into  the uploads folder with all the other files that are uploaded to a post. I don't add them as posts, as they are never needed outside of certain specific uses. However, I would like to have these stored with the rest of the files which are associated with a post, so that they  can be easily downloaded all together. 

Is there anyway to programmatically trigger the save to GCS outside of the wp_uploader? Can you point me in the right direction on how to do this?

Thanks!!

**Comment by andypotanin** [comment]
@JessBoctor Well, to keep things organized, we believe that any file that WP-Stateless will be tracking and handling must be in the Media library as a "registered" object. 

If it's not in the Media library then we ignore it - simply because tracking all other files without having a standard place to record their state and history could becoming unmanageable.

Are there security reasons you don't want to register your pgraph charts as Media items, or do you simply not have a quick way of doing it?

**Comment by JessBoctor** [comment]
Hi @andypotanin, thanks for the reply!

The main reason I didn't go through the typical uploader process is that files are constantly being rewritten. Every time a post is saved, the graphs are recalculated, recreated, and then saved over the older version within the directory. Since the only use for the files was to add them to a PDF output, I didn't see the need to add them to the library for user access. 

If Stateless ignores the files entirely, then it shouldn't be a problem since the files aren't necessary to the stateless directories (IE, if the user wanted to download the directory), and they are small enough that keeping a local version on the server shouldn't be a problem.

If there is a quick way to add them to the media library and update them over and over again with the same attachment ID, I would be open to that as well. I just hadn't looked into it up until this point. Thank you for the idea.

**Comment by andypotanin** [comment]
@JessBoctor I see. So you have some files that are kind of in the gray area between cache and asset files. We actually have a similar issue with Site Origin page builder plugin that keeps re-generating some CSS files and updating them in the `wp-content/uploads` directory. 

We've considered having stateless start "discovering" them - because almost all of our sites run across multiple distributed containers so we don't want to have any local files that are not stored in SVN.

I think one of the things to consider is this - Google Cloud Storage isn't very good at updating files. In fact, they prefer for you to create new ones, I believe.

**Comment by JessBoctor** [comment]
Thanks for the tip @andypotanin! I will see if I can't just delete the old files and put new ones into the Google Cloud Storage without having to use the WP Uploader.
