### ISSUE TITLE
Known security vulnerabilities in dependencies?

### ISSUE THREAD

**Issue by zackseuberling** [udx/wp-stateless#172]
I'm currently using WP Stateless in a project with the code hosted on Github and received an alert about JS vulnerabilities in the `package.json` associated with the WP Stateless plugin.

![screen shot 2017-11-18 at 6 12 53 pm](https://user-images.githubusercontent.com/1609558/32986683-3e9a7718-cc8c-11e7-8ac6-f34efdd207fb.png)

Is this problematic? A cause for concern?

**Comment by ewsopp** [comment]
@zackseuberling thanks for reporting. We'll investigate!

**Comment by antonkorotkov** [comment]
Hey @zackseuberling 

You can ignore this. `package-lock.json` is notifying that vulnerabilities exist in Node modules we used while developing the plugin. But before every plugin release our builder script deletes all the Node modules from the plugin directory (there is no `node_modules` folder in plugin). Next release versions will not have such warning because we will delete this `package-lock.json` file since it is not needed. Our builder script did not delete it before release because it did not know about it yet. But it does now.

So, don't worry - it is safe to use WP-Stateless.

Thanks.
