### ISSUE TITLE
GCP API error during setup: "Callers must accept Terms of Service"

### ISSUE THREAD

**Issue by danyell-hubrix** [udx/wp-stateless#190]
Steps to reproduce: attempt to install/initialize WP-Stateless with a Google UserID that has _never_ connected to GCP Console. That user will not have accepted GCP Terms of Service and GCP API calls will fail.

All you see in Wordpress Admin UI is the somewhat cryptic: "Callers must accept Terms of Service"

Interactively logging in to GCP Console using the same credentials provided to WP-Stateless, then resuming the install, solves the problem.

So, the minor issue still worth correcting in WP-Stateless source would be to provide 1 extra line of human-readable error message, along the lines of "Please Connect once to GCP Console using the Google ID you provided _before_ proceeding with WP-Stateless setup" or something along those lines.

**Comment by alimuzzaman** [comment]
@danyell-hubrix @ewsopp Does this sounds good?
![image](https://user-images.githubusercontent.com/6744156/42137464-9a47cd82-7d8e-11e8-8cc3-16f258051168.png)

**Comment by ewsopp** [comment]
@alimuzzaman does the GCP API allow us to accept the TOS on behalf of the user?

**Comment by alimuzzaman** [comment]
@ewsopp 
Didn't find anything on docs.
Maybe not possible.

**Comment by ewsopp** [comment]
Alright, I think we may need to revise our setup assistant process. I'll come back here.

**Comment by ewsopp** [comment]
We need to move this to a separate milestone. Moving out of v2.1.6 for now.

**Comment by Redjo** [comment]
@ewsopp @alimuzzaman Hi guys, 

After some googling I saw you ran into the same issue as me, just right now.
"Callers must accept Terms of Service" when it is their first GCP project.

Did you guys found any solution to this issue?
Like allowing us to accept the TOS on behalf of the user or anything?

It would be AWESOME!

**Comment by alimuzzaman** [comment]
> Did you guys found any solution to this issue?

No.

**Comment by ewsopp** [comment]
I believe this issue has self resolved. 
 
I did some testing on Wednesday, March 25, 2020 with WP-Stateless v2.3.2 and I was not able to replicate. During my testing with a Google account not previously used on GCP, the setup assistant sent me to Google Cloud directly to create my billing account. Google Cloud forced me to accept the GCP TOS and thus resolved the problem described here. 
 
I'm closing this issue for now. If others are experiencing a similar problem, please reopen and provide a detailed account so that we can replicate. Thanks
