### ISSUE TITLE
WP Smush don't work in Stateless mode

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#230]
https://wordpress.org/support/topic/wp-stateless-wp-smush/

https://wordpress.org/plugins/wp-smushit/

Related issue #202

**Comment by alimuzzaman** [comment]
I found it working in Stateless mode in my testing.
First image is with WP Smush disabled and second one with WP Smush enabled.
 ![image](https://user-images.githubusercontent.com/6744156/38928582-1b04f5d8-432b-11e8-9d88-ccb301cb6298.png)

**Comment by UmeshSingla** [comment]
@ewsopp I've dropped you a email as well.

1. Media is updated by the hook in here: 
```add_filter( 'wp_update_attachment_metadata', array( $this, 'add_media' ), 100, 2 );```
https://github.com/wpCloud/wp-stateless/blob/fea18167bac57395560eed57474d90f44921df04/lib/classes/class-bootstrap.php#L213

2. Which in turn calls: 
```$media = $client->add_media()``` with respective args.

https://github.com/wpCloud/wp-stateless/blob/198ed3a771b05d5b4aa043c9448d21081ccff608/lib/classes/class-utility.php#L233

3. Before adding the image, it checks if the media already exists:
```if ( $media = $this->media_exists( $name ) ) {```
https://github.com/wpCloud/wp-stateless/blob/7522c52d5282f35abee6317b1fb0ca523faef183/lib/classes/class-gs-client.php#L196

And if it does, "// If media exists we just return it", the media object is returned as it is, and not checked for metadata changes. 

Optimised image have all the attributes same, just the metadata is updated, so in order to allow the optimised image to be synced, you might need to check for metadata changes and update the object if any.

Let me know, if I missed something in there.

**Comment by UmeshSingla** [comment]
@alimuzzaman Not sure, How Smush is working for you in Stateless mode. Because Smush looks for local files and in stateless mode images are deleted from local directory.

I've been testing the plugin in CDN mode.

**Comment by antonkorotkov** [comment]
@UmeshSingla So just for clarification - WP-Stateless works correctly with Smush in all modes except `Stateless` because of absence of local files?

**Comment by alimuzzaman** [comment]
Thanks @UmeshSingla, 
Yes, that is how WP Stateless work and we can check for metadata changes.
Although we made some changes in this function.
`if ( !$force && $media = $this->media_exists( $name ) ) {` force arg can be use to overwrite image.
https://github.com/wpCloud/wp-stateless/blob/2a61daadbfb672091211bb75396c71f0d146b238/lib/classes/class-gs-client.php#L197

Can you please explain how **WP Smush** work? What hook or filter we can use for **Sateless mode**?

**Comment by alimuzzaman** [comment]
I made the required changes and it's working now in both CDN and Stateless mode.
You can download it from [here](https://github.com/wpCloud/wp-stateless/archive/5bf44bacd9cfc4af8911e7f5e85a17d9fce610a2.zip) for [testing](https://github.com/wpCloud/wp-stateless/tree/develop-alim).

**Comment by alimuzzaman** [comment]
We need to improve the performance.
Currently it uploading images to GCS twice.

1. Once immediately.
2. Once again after compression. 

@UmeshSingla is there a way to check if a image is added to async queue, so that we can avoid first upload.

**Comment by UmeshSingla** [comment]
@antonkorotkov @alimuzzaman So sorry guys I missed the whole communication in here. Been taken up a bit, will check it out over the weekend.

**Comment by Mashenka** [comment]
@UmeshSingla while testing be sure you have enabled compatibility in Stateless Settings/Compatibility tab

**Comment by davidcommarmond** [comment]
Hello,
Compatibility setting for WP Smush is not available if your have WP Smush Pro (The paid version of the plugin). Can you add for pro as well please ?

**Comment by ewsopp** [comment]
@Mashenka @alimuzzaman can you reach out to them and see if we can get a license for testing?

**Comment by av3nger** [comment]
@ewsopp , there isn't any difference between the two versions. Unless, you are somehow using the plugin or directory name.
protected $plugin_file = 'wp-smushit/wp-smush.php';
The Pro version plugin folder is 'wp-smush-pro/wp-smush.php';

**Comment by alimuzzaman** [comment]
@av3nger 
It should be working with the [2.1.8 RC 3](https://github.com/wpCloud/wp-stateless/releases/tag/2.1.8-RC3) version.

`wp-smush-pro/wp-smush.php` has been included in the RC3.
