### ISSUE TITLE
 The STATELESS media mode

### ISSUE THREAD

**Issue by mjezegou** [udx/wp-stateless#234]
I would like use this config (in wp-config) and like on the readme.md : 

define( 'WP_STATELESS_MEDIA_BUCKET', 'media.application-domain.com' );
define( 'WP_STATELESS_MEDIA_MODE', 'stateless' );
define( 'WP_STATELESS_MEDIA_KEY_FILE_PATH', '/var/www/wp-content/keys/application-name-service-id.p12' );
define( 'WP_STATELESS_MEDIA_SERVICE_ACCOUNT', '12345689-hash@developer.gserviceaccount.com' );

I work with docker and this config is so better !

The media mode for my project is **STATELESS** and multisite.

But in database, this option 'sm_mode' stay at 'disabled' and all option of plugin not exists.

Is it possible to work with the STATELESS media mode shortly?

Thank.

**Comment by alimuzzaman** [comment]
Hi @mjezegou, sorry for our late replay.
Constants doesn't change option in database. When constant is defined we use constant value instead of database value. 
Unless you try to save the settings from settings page the value in option will not be changed.
Can you please explain what is the problem exactly?

**Comment by alimuzzaman** [comment]
@mjezegou if you need to get the settings you can use our `ud_get_stateless_media()` function.
For example 

- `ud_get_stateless_media('sm')` will return all the stateless settings as array.
- `ud_get_stateless_media('sm.mode')` will return the mode.
