### ISSUE TITLE
CSS Files created by Elementor don't be copied to GCS

### ISSUE THREAD

**Issue by sebascontre** [udx/wp-stateless#235]
The folders Elementor creates, appear on GCS, but not the css files

**Comment by markokhman** [comment]
Hi guys
Who is responsible for that?
Any ideas on where we can start? My team seems to really need this feature, what should we do?

**Comment by markokhman** [comment]
Any ideas on the implementation, we are ready to contribute, but so far we didnt code anything in wp-stateles

So the wp-stateless is able to rewrite urls of html when wordpress serves those 
But can wp-stateless rewrite css files and serve rewritten css file?

**Comment by alimuzzaman** [comment]
@markusila Sorry for the late. Looking into this right now.

> So the wp-stateless is able to rewrite urls of html when wordpress serves those

WP-Stateless doesn't rewrite url in html. It's only rewrite url in post content and post meta. 

>But can wp-stateless rewrite css files and serve rewritten css file?

We can support them through filters of Elementor. We need to find how they create the css files and use in frontend.

We create compatibility to support other plugins. 
You can find them in [`wp-stateless\lib\classes\compatibility\`](https://github.com/wpCloud/wp-stateless/tree/latest/lib/classes/compatibility) dir.

**Comment by alimuzzaman** [comment]
@sebascontre @markusila 
Can you please test how this work with this updates.
I was able to find two types of css file `global.css`, `post-xx.css`.

CSS files are getting synced when page viewed. And `post-xx.css` getting deleted on page update/delete.
`global.css` seems to be static.

https://github.com/wpCloud/wp-stateless/blob/develop-alim/lib/classes/compatibility/elementor.php

You can get the update from here:
https://github.com/wpCloud/wp-stateless/releases/tag/2.1.8-beta-2

**Comment by hamid159** [comment]
Hi @alimuzzaman ,
Thanks for making update on CSS files syncing. But there is one more problem related with it. Inside `post-xx.css` files there are image links as well that are served using `background-image` (as far as I know) attribute of CSS.
But after syncing all images from WP Stateless Settings, Elementor still serve those images from the WP media library not from GCS. I think this is because elementor saves its widget data in `_elementor_data` post meta and the link of image is also saved there. but WP stateless doesn't change that link to serve from GCS.

**NOTE:** This does not work only for past posts. For new posts, images inside CSS file are served from GCS.

### How you can test it
- Install & activate [Elementor](https://github.com/pojome/elementor) and [Elementor Pro](https://github.com/wp-premium-themes/elementor-pro) plugin.
- Create post and insert `Slides` widget inside post using Elementor Editor.
- Save the post.
- Now sync images using WP Stateless.
- Open post-{postid}.css file, you will see that slider image is being served from WP media library not GCS.

Please let me know if you need any more clarification about this issue.

Thanks!

**Comment by alimuzzaman** [comment]
@hamid159 
Yes it's saved in `_elementor_data`.
I am not sure how we can handle that. 

We can hook into `save_post` and alter the `_elementor_data` meta.

**Comment by hamid159** [comment]
@alimuzzaman 
Actually we cannot hook into `save_post` as it triggers when we save post. As I said before that the already system works great for new posts.

To change image urls in CSS file for already created/previous posts, I think you will need to iterate through each `post-xx.css` file and replace the local urls with GCS url. There might be other solutions, but this one is in my mind right now.

**Comment by alimuzzaman** [comment]
@hamid159 
Can you please test? 
Try **Stateless Settings** >> **Sync Tab** >> `Synchronize non media library files between Google Storage and local server`
https://github.com/wpCloud/wp-stateless/tree/55e5da42edf5bbe6873575d182574bdfdcd498e6
