### ISSUE TITLE
refine admin notice messages

### ISSUE THREAD

**Issue by ewsopp** [udx/wp-stateless#276]
We have a new admin notice design now. Lets review all our notices and refine the text and presentation of each.

To start, please list all the messages we currently output and describe what causes them to be displayed.

**Comment by alimuzzaman** [comment]
@ewsopp is this sounds good?
`Unknown failure reason.` to `No metadata generated for imge_title (ID image_id).`

Sync field because no metadata was generated for image.

Here is a example of message when success `Polo (ID 192) was successfully resized in 10.828 seconds.`

**Comment by alimuzzaman** [comment]
`is_connected_to_gs`
Could not connect to Google Storage bucket. Please, be sure that bucket with name <b>%s</b> exists.

`When have conflict`
%s plugin may have potential Google SDK version conflicts with %s plugin. %s is using Google SDK %s, when %s loads old Google SDK version %s.

`PHP_VERSION < 5.5`
The plugin requires PHP %s or higher. You current PHP version %s is too old.

``
WordPress looks at local files to prevent files with the same filenames. 
                                Since Stateless mode bypasses this check, there is a potential for files to be stored with the same file name. We enforce the Cache-Busting option to prevent this. 
                                Override with the \<a href='%s' target='_blank'>%s</a> constant.

``
%s: Deprecated Notice (%s)
<i>%s</i> constant is deprecated, please use <i>%s</i> instead.

``
%s: Compatibility for %s isn't enabled.
Please enable the compatibility to ensure the fnctionality will work properly between <b>{$this->title}</b> and <b>WP-Stateless</b>.

`\wp-stateless\vendor\usabilitydynamics\lib-wp-bootstrap\lib\classes\class-bootstrap.php`

`composer_dependencies()`
Module <b>%s</b> is not installed or the version is old, class <b>%s</b> does not exist.

`composer_dependencies()`
Module <b>%s</b> should be updated to the latest version, class <b>%s</b> must have version <b>%s</b> or higher.

``
Class \UsabilityDynamics\UD_API\Bootstrap does not exist. Be sure all required plugins and (or) composer modules installed and activated.

``
Licenses client can not be activated due to invalid \'licenses\' schema.

``
Product requires license, but product ID and (or) referrer is undefined. Please, be sure, that license schema has all required data.

**Comment by Mashenka** [comment]
@ewsopp that probably had to be you on this task

**Comment by ewsopp** [comment]
Alright, I removed it from the v2.1.8 milestone. I won't be able to get to it in time for the release this week.
