### ISSUE TITLE
REMOVE "Stateless mode now requires the Cache-Busting option" Notice!!!

### ISSUE THREAD

**Issue by leepeterson** [udx/wp-stateless#296]
CDN Mode is selected. It's set via UI dropdown; set via database option; set via constant. STATELESS MODE IS NOT SET.

This issue has persisted across several websites for over a month.

When is it going to be fixed? The banner persists across all admin pages, for all users, and it's incorrect and quite useless.

**Comment by ewsopp** [comment]
@leepeterson thanks for reporting.

@alimuzzaman please investigate this issue for the next release.

**Comment by alimuzzaman** [comment]
@leepeterson 
What do you mean?
> CDN Mode is selected. It's set via UI dropdown; set via database option; set via constant. STATELESS MODE IS NOT SET.

**Comment by alimuzzaman** [comment]
@ewsopp @leepeterson 
This is how it should work according to #279. The problem was Notice wasn't dismissible in the released version because of a JavaScript error.

This problem have fixed in the [2.1.8 RC 3](https://github.com/wpCloud/wp-stateless/releases/tag/2.1.8-RC3).

@leepeterson once you **dismissed the notice**, notice won't show again in the future.
