### ISSUE TITLE
Access same cloud storage bucket from two different sites?

### ISSUE THREAD

**Issue by benneynens** [udx/wp-stateless#308]
Is it possible (or are there any plans to implement in future) an ability to access the same bucket from more than one wordpress site?

In my case this would be useful as I have a couple of sites that use many of the same images.

Amazing plugin by the way!

**Comment by dchenk** [comment]
@benneynens the way to do this is to specify different strings for the “Bucket Folder” setting. Each site should have its own “folder.”

**Comment by benneynens** [comment]
Apologies for my slow response.  I think your meaning is a little different to what I intend.

My objective is to have more than one website accessing the same bucket of images.  Ideally, the wordpress meta data for each image can also be synced.

I understand this is probably an ambitious objective but I thought it worth asking.

Definitely appreciate your feedback either way ;)

**Comment by walle89** [comment]
I'm not sure what's the use case is, but you maybe want to look at plugin like if you have a multisite installation: https://wordpress.org/plugins/network-shared-media/

Otherwise the main issue that's needs to be solved how to sync media libraries from two different databases, and I don't think it's easy to find a solution for. Why not then upload to a common third party media storage host (and integrate it with a plugin)?

**Comment by benneynens** [comment]
Thanks for your thoughts on that.  I decided that the idea I was trying to implement was just introducing unnecessary complication.  Much appreciate your feedback though.
