### ISSUE TITLE
Some compatibility having issue if root dir is set.

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#368]
https://wordpress.org/support/topic/css-not-working-through-siteorigin-css/

In some compatibility  root dir isn't included in the returning URL.

We need to apply `wp_stateless_bucket_link` filter.

**Comment by antonkorotkov** [comment]
@alimuzzaman do you need me to work on this? I see you do commits.

**Comment by alimuzzaman** [comment]
@antonkorotkov no.

**Comment by antonkorotkov** [comment]
@alimuzzaman can you confirm the order of these lines is correct?

https://github.com/wpCloud/wp-stateless/blob/a294525d400aa276352e2aec61c897608610d01a/lib/classes/compatibility/gravity-forms.php#L67-L69

The `$name` is being redeclared in line 67 and 69 and used in between of them. That is correct and intentional?

**Comment by alimuzzaman** [comment]
@antonkorotkov yes it's intentional. `wp_stateless_file_name` filter add root dir. Which should not be in local path.
