### ISSUE TITLE
Why not sync the entire `wp-content/uploads` 

### ISSUE THREAD

**Issue by andrewmclagan** [udx/wp-stateless#389]
Why not sync the entire `wp-content/uploads`  - directory as other cloud storage plugins do?

https://github.com/humanmade/S3-Uploads

**Comment by hirenshah** [comment]
Anyone going to actually reply to these issues?

**Comment by andrewmclagan** [comment]
I think this is a dead repo...

**Comment by andrewmclagan** [comment]
Would you consider transferring them?

**Comment by hirenshah** [comment]
> I think this is a dead repo...

Last update was 5 days ago, so looks pretty active to me 🙂

**Comment by alimuzzaman** [comment]
Hi @andrewmclagan,

Sorry for the late replay.

It is possible for us to Sync the entire `wp-content/uploads` but because every plugin/theme handles there file different way, we can't write a single logic that will ensure uses of GCS URL.

That's why we handle files of each plugin separately. Check **Stateless Settings** >> **Compatibility** tabs for supported plugins.

Hoping that answer your question.
