### ISSUE TITLE
Update broke organization

### ISSUE THREAD

**Issue by alimuzzaman** [udx/wp-stateless#436]
https://wordpress.org/support/topic/update-broke-organization/

> After the most recent update on 1/13/2020, the organization feature is broken. Images are only getting as far as the year for organization rather than month and there is a 0 being prefixed to the front of the images.

**Comment by alimuzzaman** [comment]
Wasn't able to replicate.

**Comment by koganas** [comment]
Hi, this issue is happening in a multisite installation that i am working on.

I have 2 sites with the same settings. One in English, the other one in portuguese.
The english site is working fine. But in the portuguese version this problem started since the beginning of this month (may 2020).

All images uploaded are returning with a broken path as described:
`/5/2020/0latam-investimentos.jpg`
`/5/2020/0Tatiana-Pimenta-Vittude-scaled.jpg`

Apparently it is a bug with the month path, that is not returning the right way.

Settings:
CDN
Organization: enabled
Cache-busting: disabled

Compatibility
Dynamic image support: disabled
WP Smush: enabled

Plugin version 2.3.2 (latest)
WP version 5.3.2

Obs.:
My bucket folder is `/5`, same as the month. Could it be a conflict with that? Since the english version runs in `/6/` and it is working just fine for now.

**Comment by koganas** [comment]
I've tested changing the bucket folder to a random name and the folder organization works fine. This might be a conflict when the bucket folder has the same number as the month.

**Comment by koganas** [comment]
Updates about this issue:
Now that we are in June (month 6), my english version started with this same broken path issue (bucket folder `/6/`). The portuguese version is working fine with bucket folder `/5/`.

So i still think this is a conflict when the bucket folder has the same number as the month.

**Comment by planv** [comment]
Hello @koganas 

Is issue still relevant after update to version 3.1?

**Comment by maikelvl** [comment]
@planv Yes, I've got this issue in v3.1.0. (Wordpress v5.5.3)

**Comment by maikelvl** [comment]
Found the solution to my problem in https://github.com/udx/wp-stateless/issues/493#issuecomment-649231809

I did not realise the year/month variables needed to be defined as well:

```diff
-define("WP_STATELESS_MEDIA_ROOT_DIR", "media");
+define("WP_STATELESS_MEDIA_ROOT_DIR", "media/%date_year/date_month%");
```
