### ISSUE TITLE
handle PDF thumbnails

### ISSUE THREAD

**Issue by antonkorotkov** [udx/wp-stateless#577]
Looks like thumbnails are being generated for PDFs. 

Example:

![image](https://user-images.githubusercontent.com/2276882/95843976-0c037f80-0d51-11eb-931a-0ff4b0950f00.png)

But they are not being deleted after syncing in Ephemeral mode. I think this is something relatively new. And it is not related to the background processing.

**Comment by planv** [comment]
Current issue with removing thumbnails in `Ephemeral` mode fixed.

Also I noticed that we don't create thumbnails for PDF in `Stateless` mode, it is due to using `WP_Image_Editor_GD` (for `StreamWrapper` that doesn't save file locally) instead 'WP_Image_Editor_Imagick' (need for generating thumbnails for PDF - https://make.wordpress.org/core/2016/11/15/enhanced-pdf-support-4-7/ ).
@ewsopp Should we add notice about that?

**Comment by ewsopp** [comment]
I think so, but when would we display it? and what would it say?

**Comment by planv** [comment]
@ewsopp 

I guess here 

![image](https://user-images.githubusercontent.com/5268508/96598734-d84bcb00-12f7-11eb-9f79-f7a734414b1e.png)

`
Store and serve media files with Google Cloud Storage only. Media files are not stored locally, but local storage is used temporarily for processing and is required for certain compatibilities, generating thumbnails for PDF documents.
`
